# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
