# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 17:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_auto_20160317_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='likesuser',
            name='user',
            field=models.ForeignKey(null=True,on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
