# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_auto_20160307_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='photo',
            field=models.ImageField(upload_to='gifty'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'Public'), ('PRIV', 'Private')], default='PUB', max_length=4),
        ),
    ]
