# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 19:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160312_2000'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifts', '0004_auto_20160310_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentGift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='GiftsCharts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='GiftsMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('PUB', 'Public'), ('PRIV', 'Private')], default='PUB', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreGift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='gift',
            name='prize',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='gift',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gift',
            name='photo',
            field=models.ImageField(upload_to='gifts/Files/'),
        ),
        migrations.AddField(
            model_name='scoregift',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifts.Gift'),
        ),
        migrations.AddField(
            model_name='scoregift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='list',
            name='gifts',
            field=models.ManyToManyField(through='gifts.GiftsMember', to='gifts.Gift'),
        ),
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftsmember',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifts.Gift'),
        ),
        migrations.AddField(
            model_name='giftsmember',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifts.List'),
        ),
        migrations.AddField(
            model_name='giftscharts',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifts.Gift'),
        ),
        migrations.AddField(
            model_name='commentgift',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifts.Gift'),
        ),
        migrations.AddField(
            model_name='commentgift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
