# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0005_auto_20160312_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='gift',
            name='photo',
            field=models.ImageField(upload_to='gifts'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='prize',
            field=models.FloatField(),
        ),
    ]
