# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160317_1741'),
        ('gifts', '0006_auto_20160316_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
